language: smalltalk
sudo: false

# Select operating system(s)
os:
  - linux

# Select compatible Smalltalk image(s)
smalltalk:
  - Pharo-alpha
  - Pharo-stable
  - Pharo-7.0
  - Pharo-6.1
  - Pharo-6.0
  - Pharo-5.0
  
  - Pharo64-alpha
  - Pharo64-stable
  - Pharo64-7.0
  - Pharo64-6.1
  - Pharo64-6.0
